In [10]:
import pandas as pd

In [11]:
groundwater = pd.read_csv(r"C:\Users\vishn\Desktop\Programs\CodeOClock\groundwater\ZIP\7063\7063_KEYS.csv")

In [13]:
groundwater.head()

,srcStateName,srcDistrictName,srcMonth,srcYear,YearCode,Year,MonthCode,Month,Country,StateCode,...,WeighingRatio_NumberOfHouseholdsUrban,WeighingRatio_Percentage_NumberOfHouseholdsUrban,WeighingRatio_NumberOfHouseholdsRural,WeighingRatio_Percentage_NumberOfHouseholdsRural,WeighingRatio_LandAreaUrban,WeighingRatio_Percentage_LandAreaUrban,WeighingRatio_LandAreaRural,WeighingRatio_Percentage_LandAreaRural,WeighingRatio_LandArea,WeighingRatio_Percentage_LandArea
0,JAMMU & KASHMIR,ANANTNAG,Apr - 2011,2011,2011,"Calendar Year (Jan - Dec), 2011",201104,"April, 2011",India,1,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,JAMMU & KASHMIR,ANANTNAG,Apr - 2012,2012,2012,"Calendar Year (Jan - Dec), 2012",201204,"April, 2012",India,1,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,JAMMU & KASHMIR,ANANTNAG,Apr - 2013,2013,2013,"Calendar Year (Jan - Dec), 2013",201304,"April, 2013",India,1,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,JAMMU & KASHMIR,ANANTNAG,Apr - 2014,2014,2014,"Calendar Year (Jan - Dec), 2014",201404,"April, 2014",India,1,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,JAMMU & KASHMIR,ANANTNAG,Apr - 2015,2015,2015,"Calendar Year (Jan - Dec), 2015",201504,"April, 2015",India,1,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [15]:
groundwater.describe()

,srcYear,YearCode,MonthCode,StateCode,DistrictCode,TotalPopulation,TotalPopulationUrban,TotalPopulationRural,TotalPopulationMale,TotalPopulationMaleUrban,...,WeighingRatio_NumberOfHouseholdsUrban,WeighingRatio_Percentage_NumberOfHouseholdsUrban,WeighingRatio_NumberOfHouseholdsRural,WeighingRatio_Percentage_NumberOfHouseholdsRural,WeighingRatio_LandAreaUrban,WeighingRatio_Percentage_LandAreaUrban,WeighingRatio_LandAreaRural,WeighingRatio_Percentage_LandAreaRural,WeighingRatio_LandArea,WeighingRatio_Percentage_LandArea
count,112751.000000,112751.000000,112751.000000,112751.000000,112751.000000,1.120660e+05,1.120660e+05,1.127510e+05,1.120660e+05,1.120660e+05,...,112066.000000,112066.000000,112751.000000,112751.000000,105490.000000,107956.000000,102065.000000,106723.000000,101928.000000,105627.000000
mean,2016.218978,2016.218978,201628.270073,18.578372,379.091130,1.467716e+06,4.558965e+05,1.005718e+06,7.552500e+05,2.361551e+05,...,0.765281,0.872861,0.758202,0.874848,0.787013,0.890863,0.795973,0.898588,0.799731,0.904021
std,3.301674,3.301674,329.961813,9.760148,213.179745,1.458577e+06,8.595787e+05,9.663848e+05,7.560263e+05,4.503301e+05,...,0.380152,0.311591,0.370519,0.313491,0.359068,0.293057,0.351355,0.284814,0.345869,0.275235
min,2011.000000,2011.000000,201101.000000,1.000000,1.000000,6.400000e+01,0.000000e+00,0.000000e+00,3.000000e+01,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000067,0.000043
25%,2013.000000,2013.000000,201311.000000,9.000000,199.000000,3.819560e+05,4.814000e+04,2.158160e+05,1.973940e+05,2.459100e+04,...,0.544030,1.000000,0.449585,1.000000,0.654266,1.000000,0.622866,1.000000,0.653746,1.000000
50%,2016.000000,2016.000000,201609.000000,19.000000,383.000000,1.137466e+06,2.038045e+05,8.148770e+05,5.853625e+05,1.063455e+05,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,2019.000000,2019.000000,201907.000000,27.000000,568.000000,2.043355e+06,4.837640e+05,1.412835e+06,1.056520e+06,2.495910e+05,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2022.000000,2022.000000,202205.000000,38.000000,737.000000,1.000978e+07,9.356962e+06,5.703115e+06,5.119389e+06,5.031323e+06,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000